name: KiCAD PCM packaging

permissions:
  contents: write
  releases: write

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  create_archive:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Create archive
        run: |
          chmod +x ./PCM/create_pcm_archive.sh
          ./PCM/create_pcm_archive.sh "${{ github.event.release.tag_name }}"

      - name: Upload zip as asset to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.PERSONAL_TOKEN }}
          file: ./PCM/KiCAD-PCM-${{ github.event.release.tag_name }}.zip
          asset_name: KiCAD-PCM-${{ github.event.release.tag_name }}.zip
          overwrite: true
          tag: ${{ github.event.release.tag_name }}