name: KiCAD PCM packaging

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  create_archive:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Create archive
        run: |
          chmod +x ./PCM/create_pcm_archive.sh

          if [ "${{ github.event_name }}" = "release" ]; then
            VERSION="${{ github.event.release.tag_name }}"
          else
            VERSION="${GITHUB_REF_NAME}"
          fi

    echo "Using VERSION=$VERSION"
    ./PCM/create_pcm_archive.sh "$VERSION"

      - name: Compute SHA256 and size
        id: meta
        run: |
          FILE=./PCM/KiCAD-PCM-${{ github.event.release.tag_name }}.zip

          SHA=$(sha256sum "$FILE" | awk '{print $1}')
          SIZE=$(stat -c%s "$FILE")

          echo "SHA256=$SHA" >> $GITHUB_OUTPUT
          echo "SIZE=$SIZE" >> $GITHUB_OUTPUT

      - name: Upload zip as release asset
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.PERSONAL_TOKEN }}
          file: ./PCM/KiCAD-PCM-${{ github.event.release.tag_name }}.zip
          asset_name: KiCAD-PCM-${{ github.event.release.tag_name }}.zip
          overwrite: true
          tag: ${{ github.event.release.tag_name }}

      - name: Trigger repository rebuild
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Rebuild repository
          ref: refs/heads/master
          repo: KoenLammers/Yanndroid-KiCAD-Repository
          token: ${{ secrets.PERSONAL_TOKEN }}
          inputs: |
            {
              "VERSION": "${{ github.event.release.tag_name }}",
              "DOWNLOAD_SHA256": "${{ steps.meta.outputs.SHA256 }}",
              "DOWNLOAD_SIZE": "${{ steps.meta.outputs.SIZE }}",
              "DOWNLOAD_URL": "https://github.com/KoenLammers/KiCAD-EasyEDA-Parts-V2/releases/download/${{ github.event.release.tag_name }}/KiCAD-PCM-${{ github.event.release.tag_name }}.zip"
            }